# Site settings
title: opensx70.com
email: sx70@opensx70.com
description: > # openSX70 is the home of the Arduino-based and open-sourced modification of the classic Polaroid SX70 camera.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
disqus: opensx70-com
enable_retina: false
permalink: :title
nav_list:
  Home : ['Home', '/', 'fa-camera']
  #Home_Alt : ['Home Alt', '/home-alt', 'fa-home']
  #Home_Alt_2 : ['Home Alt 2', '/home-alt-2/', 'fa-home']
  About : ['About', '/about', 'fa-quote-left']
  FAQ : ['FAQ', '/FAQ', 'fa-question-circle']
  Tutorials : ['Tutorials', '/tutorials', 'fa-wrench']
  Links : ['Links', '/links', 'fa-external-link-square']
  Press : ['Press', '/contact', 'fa-newspaper-o']
  Files : ['Files', '/files', 'fa-files-o']
  Author : ['Author', '/author/joaquin', 'fa-user']
single_footer: '<p>Welcome to the openSX70 community &copy; 2017 <a href="/">latest posts</a></p>'
footer_links:
    About: ['About', '/about']
#    Writer: ['Writer 2016', '/about']
    Writer: ['openSX70 2017', '/about']


# Build settings
# markdown: kramdown

include:
  - _pages
 
prose:
  # Configurations ...
  rooturl: ""
  siteurl: 'http://opensx70.com/'
  media: 'img'
  metadata:
    _posts:
      - name: 'layout'
        field:
          element: 'hidden'
          value: 'post'
      - name: 'title'
        field:
          element: text
          placeholder: Write Post Title Here
          label: Post Title
          type: text
      - name: description
        field:
          element: text
          label: Post Description
          placeholder: Write Description Here
      - name: date
        field:
          element: text
          label: Post Date
          value: CURRENT_DATETIME
      - name: author_name
        field:
          element: text
          label: Author's Name
          value: Joaquín de Prada
      - name: author_url
        field:
          element: text
          label: Author's URL
          value: '/author/joaquin'
      - name: author_avatar
        field:
          element: text
          label: Author's Avatar
          value: joaquin
      - name: 'show_avatar'
        field:
          element: hidden
          value: true
      - name: 'comments'
        field:
          element: select
          label: Are comments enabled?
          options:
            - name: Yes
              value: true
            - name: No
              value: false
      - name: 'published'
        field:
          element: button
          label: Publish?
          on: Published
          off: Unpublished

  _pages:
    - name: "layout"
      field:
        element: "hidden"
        value: "page"