# Site settings
title: OpenSX70
email: sx70@opensx70.com
description: > # openSX70 is the home of the Arduino-based and open-sourced modification of the classic Polaroid SX70 camera.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
disqus: opensx70-com
enable_retina: false
permalink: /:title
nav_list:
  Home : ['Home', '/', 'fa-camera']
  #Home_Alt : ['Home Alt', '/home-alt', 'fa-home']
  #Home_Alt_2 : ['Home Alt 2', '/home-alt-2/', 'fa-home']
  About : ['About', '/about', 'fa-quote-left']
  FAQ : ['FAQ', '/FAQ', 'fa-question-circle']
  wiki : ['WIKI', 'https://github.com/openSX70/openSX70-Arduino-main/wiki', 'fa-external-link', 'blank']
  Tutorials : ['Tutorials', '/tutorials', 'fa-wrench']
  #Home_Alt_2 : ['Tutorials', '/tutorials', 'fa-wrench']
  Links : ['Links', '/links', 'fa-external-link-square']
  Press : ['Press', '/press', 'fa-newspaper-o']
  Files : ['Files', '/files', 'fa-files-o']
  Gallery : ['Gallery', 'https://adobe.ly/2tofFOf', 'fa-photo', 'blank']
  Author : ['Author', '/author/joaquin', 'fa-user']
  Donate : ['Donate', 'https://paypal.me/opensx70', 'fa-paypal', 'blank']

single_footer: '<p>Welcome to the openSX70 community &copy; 2018 <a href="/">latest posts</a></p>'
footer_links:
    About: ['About', '/about']
#    Writer: ['Writer 2016', '/about']
    Writer: ['openSX70 2018', '/about']

analytics:
  google                 : "UA-126751298-1"

# Build settings
# markdown: kramdown

include:
  - _pages
  - _tutorials
 
collections:
  tutorials:
    output: true
    permalink: /:tutorials/:path/

paginate: 8
paginate_path: "/page/:num"

plugins:
  - jekyll-paginate

prose:
  # Configurations ...
  rooturl: ""
  siteurl: 'http://opensx70.com/'
  media: 'img'
  metadata:
    _posts:
      - name: 'layout'
        field:
          element: 'hidden'
          value: 'post'
      - name: title
        field:
          element: text
          placeholder: Post Title
          label: Post Title
          value: POST TITLE
      - name: description
        field:
          element: text
          label: Post Description
          placeholder: Write Description Here
      - name: date
        field:
          element: text
          label: Post Date
          value: CURRENT_DATETIME
      - name: author_name
        field:
          element: text
          label: Author's Name
          value: Joaquín de Prada
      - name: author_url
        field:
          element: text
          label: Author's URL
          value: '/author/joaquin'
      - name: author_avatar
        field:
          element: text
          label: Author's Avatar
          value: joaquin
      - name: 'show_avatar'
        field:
          element: hidden
          value: true
      - name: categories
        field:
          element: text
          label: Post categories
          value: opensx70
          help: Write Post Categories Here
      - name: feature_image
        field:
          element: text
          label: Featured Image path
          placeholder: For example SX70_images/openSX70-cameraporn-6
          help: Write the path of the image you want to show on the header
      - name: permalink
        field:
          element: text
          label: Post permalink
          placeholder: For example /posts/2017/12/post-20171204-flash/
      - name: read_time
        field:
          element: number
          label: Read Time
          help: Number of minutes it takes to read this post. It must be a number.
          type: number
          value: 5
      - name: comments
        field:
          element: select
          label: Comments
          help: Are comments enabled?
          options:
            - name: Yes
              value: true
            - name: No
              value: false
      - name: published
        field:
          element: select
          label: Publication
          help: Do you want the post published?
          options:
            - name: Yes
              value: true
            - name: No
              value: false
      - name: show_related_posts
        field:
          element: select
          label: Related Posts
          help: Do you want to show related posts?
          options:
            - name: Yes
              value: true
            - name: No
              value: false
    _pages:
      - name: layout
        field:
          label: Layout type
          help: Layout types are page, post, author, category, contact, home, home-alt, home-alt-2, post-no-feature, post-sidebar, with-sidebar
          element: text
          value: page
      - name: title
        field:
          element: text
          placeholder: Page Title
          label: Page Title
          value: PAGE TITLE
      - name: feature_image
        field:
          element: text
          label: Featured Image path
          placeholder: For example SX70_images/openSX70-cameraporn-6
          help: Write the path of the image you want to show on the header
      - name: permalink
        field:
          element: text
          label: Post permalink
          placeholder: For example /posts/2017/12/post-20171204-flash/
