# Site settings
title: opensx70.com
email: sx70@opensx70.com
description: > # openSX70 is the home of the Arduino-based and open-sourced modification of the classic Polaroid SX70 camera.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
disqus: opensx70-com
enable_retina: false
permalink: :title
nav_list:
  Home : ['Home', '/', 'fa-camera']
  #Home_Alt : ['Home Alt', '/home-alt', 'fa-home']
  #Home_Alt_2 : ['Home Alt 2', '/home-alt-2/', 'fa-home']
  About : ['About', '/about', 'fa-quote-left']
  FAQ : ['FAQ', '/FAQ', 'fa-question-circle']
  Tutorials : ['Tutorials', '/tutorials', 'fa-wrench']
  Links : ['Links', '/links', 'fa-external-link-square']
  Press : ['Press', '/contact', 'fa-newspaper-o']
  Files : ['Files', '/files', 'fa-files-o']
  Author : ['Author', '/author/joaquin', 'fa-user']
single_footer: '<p>Welcome to the openSX70 community &copy; 2017 <a href="/">latest posts</a></p>'
footer_links:
    About: ['About', '/about']
#    Writer: ['Writer 2016', '/about']
    Writer: ['openSX70 2017', '/about']


# Build settings
# markdown: kramdown

include:
  - _pages
 
prose:
  # Configurations ...
  rooturl: ""
  siteurl: 'http://opensx70.com/'
  media: 'img'
  metadata:
    _posts:
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
            - name: "Pears"
              value: "pears"
            - name: "Mangos"
              value: "mangos"

  _pages:
    - name: "layout"
      field:
        element: "hidden"
        value: "page"