---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: _posts
  label: Posts
  create: all
  match: "**/*"
- type: directory
  path: _tutorials
  label: Tutorials
  create: all
  match: "**/*"
- type: directory
  path: _pages
  label: Pages
  create: all
  match: "**/*"
upload_dir: img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: gem install jekyll; bundle install;
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: jekyll serve --drafts --unpublished --future -d _site
