# config.yml

display_url: https://opensx70.netlify.app
locale: 'en'
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    media_folder: '/img/{{year}}'
    path: '{{year}}/{{year}}-{{month}}-{{day}}-{{slug}}'
    nested:
      depth: 100 # max depth to show in the collection tree
      summary: '{{title}}'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Published', name: 'published', widget: 'boolean', hint: 'Enable this checkbox to publish the project so that it is visible', default: true }
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'NetlifyCMS', name: 'netlifycms', hint: 'In order to load the images correctly', widget: 'hidden', default: true }
      - { label: 'Show Avatar', name: 'show_avatar', widget: 'hidden', default: true }
      - { label: 'Author Name', name: 'author_name', widget: 'hidden', default: 'Joaquín de Prada' }
      - { label: 'Author Image', name: 'author_url', widget: 'hidden', default: '/author/joaquin' }
      - { label: 'Author Avatar', name: 'author_avatar', widget: 'hidden', default: 'joaquin' }
      - { label: 'Comments Enabled', name: 'comments', widget: 'hidden', default: true }
      - { label: 'Show Related Posts', name: 'show_related_posts', widget: 'hidden', default: true }
      - { label: 'Read Time', name: 'read_time', widget: 'hidden', value_type: "int", hint: 'Estimated time to read this article', default: '5' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Header Image', name: 'feature_image', widget: 'image' }
      - { label: 'Categories', name: 'categories', widget: 'list', required: false, default: 'openSX70' }
      - { label: 'Permalink', name: 'permalink', widget: 'string', required: false, hint: 'if empty this URL will be auto-generated.' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'tutorials'
    label: 'Tutorials'
    folder: '_tutorials/'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Show Avatar', name: 'show_avatar', widget: 'hidden', default: true }
      - { label: 'Author Name', name: 'author_name', widget: 'hidden', default: 'Joaquín de Prada' }
      - { label: 'Author Image', name: 'author_url', widget: 'hidden', default: '/author/joaquin' }
      - { label: 'square_related', name: 'square_related', widget: 'hidden', default: 'recommend-wolf' }
      - { label: 'Comments Enabled', name: 'comments', widget: 'hidden', default: true }
      - { label: 'Show Related Posts', name: 'show_related_posts', widget: 'boolean', default: true }
      - { label: 'Read Time', name: 'read_time', widget: 'number', value_type: "int", hint: 'Estimated time to read this article', default: '5' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Header Image', name: 'feature_image', widget: 'image' }
      - { label: 'Categories', name: 'categories', widget: 'list' }
      - { label: 'Permalink', name: 'permalink', widget: 'text', required: false, hint: 'if empty this URL will be auto-generated.' }
      - { label: 'Published', name: 'published', widget: 'boolean', hint: 'Enable this checkbox to publish the project so that it is visible', default: true}
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'pages'
    label: 'Pages'
    folder: '_pages/'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: select, options: ["page", "author", "contact", "home-alt-2", "home-alt"], default: 'page' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Header Image', name: 'feature_image', widget: 'image' }
      - { label: 'Permalink', name: 'permalink', widget: 'text', required: false, hint: 'if empty this URL will be auto-generated.' }
      - { label: 'Published', name: 'published', widget: 'boolean', hint: 'Enable this checkbox to publish the project so that it is visible', default: true}
      - { label: 'Body', name: 'body', widget: 'markdown' }